baseURL = "https://phasewalk.xyz"
title = "phasewalk"
languageCode = "en"
DefaultContentLanguage = "en"   # Change this to change the site's language
theme = "hugo.386"
preserveTaxonomyNames = true

[markup.goldmark.parser.attribute]
block = true
title = true

[params]
mailto = "kat@phasewalk.net"
card = "https://phasewalk1.github.io/card"
# The name to display as main title in the home page
mainpagetitle = "LET'S ALL LOVE LAIN"

# The subtitle to display under the title in the home page
mainpagesubtitle = "make me sad - make me mad - make me feel alright"

# The description of your website. It will be displayed in the home page
mainpagedesc = "This static website is not real. It's just an afterimage of your mind."

# The name to display in the copyright section in the footer
copyrightname = "LAINCHAN"

# Enables or disables the loading animations. false activates them. Default is false.
loadfastload = false

# Sets the speed for the page loading effect. Default is 1.0.
loadspeedfactor = 1.0

# Enables or disables the second flyby cursor. Default is false.
loadonepass = false

[params.copyright]
name = "LAINCHAN"

# The url to use as link in the copyright name in the footer. Leave empty to use none.
url = "https://lainchan.org"

prefix = "phasewalk"

# Text to go between copyright and hugo disclaimer (if enabled)
suffix = "built with love <3"

[menu]
# This displays buttons in the navbar to access your contents
[[menu.main]]
identifier = "about" # An unique identifier for the button
name = "About"       # A display name for the button
url = "/about/"      # The path to the content. It can lead to a single page (like here)
weight = 10          # A number to order the buttons in the navbar

[[menu.main]]
identifier = "post"
name = "All posts"
url = "/post/"      # The path can lead to a content folder too.
weight = 20

[[menu.main]]
identifier = "card"
name = "Card"
url = "/card/"
weight = 30

[taxonomies]
category = "categories"
tag = "tags"


[privacy]

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services]

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
