name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Trunk-Inject
    - uses: jetli/trunk-action@v0.4.0
    
    - name: Sync-Submodules
      run: git submodule update --remote

    - name: Trunk-Build
      run: cd phasewalk1.me && trunk build
