on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: WASM-CD
    defaults:
      run:
        shell: bash
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Cache
        uses: actions/cache@v1.2.1
        with:
          path: public/
          key: ${{ secrets.CACHE_KEY }}

      - name: Inject Trunk
        uses: jetli/trunk-action@v0.4.0
        
      - name: Inject Hugo
        uses: peaceiris/actions-hugo@v2
        
      - name: Target Wasm
        run: rustup target add wasm32-unknown-unknown
      
      - name: Sync Submodules
        run: git submodule init && git submodule update --recursive --remote
      
      - name: Trunk Build
        run: cd phasewalk1.me && trunk build
        
      - name: Reflect Artifacts
        run: bash build.sh && hugo
        
      

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_KEY }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT }}
          projectName: phasewalk1
          directory: /public
