on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run a build step here if your project requires
      
      - name: Trunk-Inject
        uses: jetli/trunk-action@v0.4.0
      
      - name: Sync-submodule
        run: git submodule update --remote
      
      - name: Trunk-Build
        run: cd phasewalk1.me && trunk build
        
      - name: Reflect Artifacts
        run: bash build.sh

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_KEY }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT }}
          projectName: phasewalk1.xyz
          directory: public
          # Optional: Switch what branch you are publishing to.
          # By default this will be the branch which triggered this workflow
          branch: main
